import assert from 'node:assert/strict'
import { test } from 'node:test'
import { fixture, cookies, origin } from './helpers/auth.mjs'
test('production auth config supports OTP migration, password login, reset and single-use tokens',async()=>{
 const f=fixture(),email='migration@example.com'
 assert.equal((await f.call('/email-otp/send-verification-otp',{email,type:'sign-in'})).status,200)
 await Promise.all(f.pending)
 const code=f.env.messages.find(m=>m.kind==='sign-in').code
 const verified=await f.call('/sign-in/email-otp',{email,otp:code});assert.equal(verified.status,200)
 const cookie=cookies(verified),session=await f.auth.session(f.request('/get-session',undefined,cookie))
 assert.equal(session.user.emailVerified,true)
 await f.auth.setPassword(f.request('/unused',undefined,cookie),'first-password-123')
 assert.equal(f.env.store.user.length,1)
 const credential=f.env.store.account.find(a=>a.providerId==='credential');assert.ok(credential.password);assert.notEqual(credential.password,'first-password-123')
 await assert.rejects(f.auth.setPassword(f.request('/unused',undefined,cookie),'overwrite-password-123'))
 assert.equal((await f.call('/sign-in/email',{email,password:'wrong-password'})).status,401)
 const login=await f.call('/sign-in/email',{email,password:'first-password-123'});assert.equal(login.status,200)
 assert.equal((await f.call('/request-password-reset',{email,redirectTo:origin+'/reset-password'})).status,200)
 await Promise.all(f.pending)
 const reset=f.env.messages.find(m=>m.kind==='reset-link')
 const callback=await f.auth.handle(new Request(reset.url));assert.equal(callback.status,302)
 const token=new URL(callback.headers.get('location')).searchParams.get('token');assert.ok(token)
 assert.equal((await f.call('/reset-password',{token,newPassword:'second-password-456'})).status,200)
 assert.equal((await f.call('/reset-password',{token,newPassword:'third-password-789'})).status,400)
 assert.equal(f.env.store.session.length,0,'reset revokes existing sessions')
 assert.equal((await f.call('/sign-in/email',{email,password:'second-password-456'})).status,200)
 assert.equal(f.env.store.user.length,1,'migration and reset keep the same identity')
 const loggedIn=await f.call('/sign-in/email',{email,password:'second-password-456'})
 const changed=await f.call('/set-password',{password:'second-password-456','new-password':'third-password-789'},cookies(loggedIn))
 assert.equal(changed.status,200)
 assert.equal((await f.call('/sign-in/email',{email,password:'third-password-789'})).status,200)
})

test('set-password requires current password, with empty input only for first setup',async()=>{
 const f=fixture(),email='first-password@example.com'
 await f.call('/email-otp/send-verification-otp',{email,type:'sign-in'});await Promise.all(f.pending)
 const registration=f.request('/sign-in/email-otp',{email,otp:f.env.messages[0].code})
 registration.headers.set('cf-connecting-ip','203.0.113.42')
 const registered=await f.auth.handle(registration)
 assert.equal((await f.auth.session(f.request('/get-session',undefined,cookies(registered)))).session.ipAddress,'203.0.113.42')
 let cookie=cookies(registered)
 assert.equal((await f.call('/set-password',{password:'','new-password':'valid-password-123'})).status,401)
 assert.equal((await f.call('/set-password',{'new-password':'valid-password-123'},cookie)).status,400)
 assert.equal((await f.call('/set-password',{password:'wrong','new-password':'valid-password-123'},cookie)).status,400)
 assert.equal((await f.call('/set-password',{password:'','new-password':'short'},cookie)).status,400)
 const setup=await f.call('/set-password',{password:'','new-password':'valid-password-123'},cookie)
 assert.equal(setup.status,200)
 assert.equal(await f.auth.session(f.request('/get-session',undefined,cookie)),null)
 cookie=cookies(setup)
 const initial=await setup.json();assert.ok(initial.token);assert.equal(initial.session.token,initial.token);assert.equal(initial.user.email,email)
 assert.equal((await f.call('/set-password',{password:'','new-password':'replacement-password'},cookie)).status,400)
 assert.equal((await f.call('/set-password',{password:'wrong','new-password':'replacement-password'},cookie)).status,400)
 const other=await f.call('/sign-in/email',{email,password:'valid-password-123'})
 const previousToken=initial.token
 const request=f.request('/set-password',{password:'valid-password-123','new-password':'replacement-password',revokeOtherSessions:false})
 request.headers.set('authorization',`Bearer ${previousToken}`)
 request.headers.set('cf-connecting-ip','203.0.113.43')
 request.headers.set('x-forwarded-for','198.51.100.99')
 const changed=await f.auth.handle(request)
 assert.equal(changed.status,200)
 const replacement=await changed.json()
 assert.notEqual(replacement.token,previousToken)
 assert.equal(replacement.session.token,replacement.token)
 assert.equal(replacement.session.ipAddress,'203.0.113.43')
 assert.equal(replacement.user.email,email)
 assert.equal(f.env.store.session.length,1,'only the replacement session remains, even if an old client sends false')
 assert.equal(await f.auth.session(f.request('/get-session',undefined,cookie)),null)
 assert.equal(await f.auth.session(f.request('/get-session',undefined,cookies(other))),null)
 const bearer=f.request('/get-session');bearer.headers.set('authorization',`Bearer ${replacement.token}`)
 assert.equal((await f.auth.session(bearer)).session.token,replacement.token)
 assert.equal((await f.auth.session(f.request('/get-session',undefined,cookies(changed)))).session.token,replacement.token)
 assert.ok(changed.headers.get('set-auth-token'))
 assert.equal((await f.call('/sign-in/email',{email,password:'replacement-password'})).status,200)
 const schema=await(await f.auth.documentation(new Request('https://api.fonteslabs.com/api/auth/openapi.json'))).json()
 const operation=schema.paths['/api/auth/set-password'].post
 assert.deepEqual(Object.keys(operation.requestBody.content['application/json'].schema.properties).sort(),['new-password','password'])
 assert.deepEqual(operation.responses['200'].content['application/json'].schema.required,['token','session','user'])
 assert.ok(operation.responses['200'].content['application/json'].schema.properties.session)
 assert.ok(!schema.paths['/api/auth/change-password'])
 assert.ok(!schema.paths['/api/onboarding/password'])
})
